package stonks2;

import java.util.Map;

public enum Industry {
	AGRICULTURAL_INPUTS,
	BUILDING_MATERIALS,
	CHEMICALS,
	SPECIALTY_CHEMICALS,
	LUMBER_AND_WOOD_PRODUCTION,
	PAPER_AND_PAPER_PRODUCTS,
	ALUMINUM,
	COPPER,
	OTHER_INDUSTRIAL_METALS_AND_MINING,
	GOLD,
	SILVER,
	OTHER_PRECIOUS_METALS_AND_MINING,
	COKING_COAL,
	STEEL,
	AUTO_AND_TRUCK_DEALERSHIPS,
	AUTO_MANUFACTURERS,
	AUTO_PARTS,
	RECREATIONAL_VEHICLES,
	FURNISHINGS_FIXTURES_AND_APPLIANCES,
	RESIDENTIAL_CONSTRUCTION,
	TEXTILE_MANUFACTURING,
	APPAREL_MANUFACTURING,
	FOOTWEAR_AND_ACCESSORIES,
	PACKAGING_AND_CONTAINERS,
	PERSONAL_SERVICES,
	RESTAURANTS,
	APPAREL_RETAIL,
	DEPARTMENT_STORES,
	HOME_IMPROVEMENT_RETAIL,
	LUXURY_GOODS,
	INTERNET_RETAIL,
	SPECIALTY_RETAIL,
	GAMBLING,
	LEISURE,
	LODGING,
	RESORTS_AND_CASINOS,
	TRAVEL_SERVICES,
	ASSET_MANAGEMENT,
	BANKS_DIVERSIFIED,
	BANKS_REGIONAL,
	MORTGAGE_FINANCE,
	CAPITAL_MARKETS,
	FINANCIAL_DATA_AND_STOCK_EXCHANGES,
	INSURANCE_LIFE,
	INSURANCE_PROPERTY_AND_CASUALTY,
	INSURANCE_REINSURANCE,
	INSURANCE_SPECIALTY,
	INSURANCE_BROKERS,
	INSURANCE_DIVERSIFIED,
	SHELL_COMPANIES,
	FINANCIAL_CONGLOMERATES,
	CREDIT_SERVICES,
	REAL_ESTATE_DEVELOPMENT,
	REAL_ESTATE_SERVICES,
	REAL_ESTATE_DIVERSIFIED,
	REIT_HEALTHCARE_FACILITIES,
	REIT_HOTEL_AND_MOTEL,
	REIT_INDUSTRIAL,
	REIT_OFFICE,
	REIT_RESIDENTIAL,
	REIT_RETAIL,
	REIT_MORTGAGE,
	REIT_SPECIALTY,
	REIT_DIVERSIFIED,
	BEVERAGES_BREWERS,
	BEVERAGES_WINERIES_AND_DISTILLERIES,
	BEVERAGES_NON_ALCOHOLIC,
	CONFECTIONERS,
	FARM_PRODUCTS,
	HOUSEHOLD_AND_PERSONAL_PRODUCTS,
	PACKAGED_FOODS,
	EDUCATION_AND_TRAINING_SERVICES,
	DISCOUNT_STORES,
	FOOD_DISTRIBUTION,
	GROCERY_STORES,
	TOBACCO,
	BIOTECHNOLOGY,
	DRUG_MANUFACTURERS_GENERAL,
	DRUG_MANUFACTURERS_SPECIALTY_AND_GENERIC,
	HEALTHCARE_PLANS,
	MEDICAL_CARE_FACILITIES,
	PHARMACEUTICAL_RETAILERS,
	HEALTH_INFORMATION_SERVICES,
	MEDICAL_DEVICES,
	MEDICAL_INSTRUMENTS_AND_SUPPLIES,
	DIAGNOSTICS_AND_RESEARCH,
	MEDICAL_DISTRIBUTION,
	UTILITIES_INDEPENDENT_POWER_PRODUCERS,
	UTILITIES_RENEWABLE,
	UTILITIES_REGULATED_WATER,
	UTILITIES_REGULATED_ELECTRIC,
	UTILITIES_REGULATED_GAS,
	UTILITIES_DIVERSIFIED,
	TELECOM_SERVICES,
	ADVERTISING_AGENCIES,
	PUBLISHING,
	BROADCASTING,
	ENTERTAINMENT,
	INTERNET_CONTENT_AND_INFORMATION,
	ELECTRONIC_GAMING_AND_MULTIMEDIA,
	OIL_AND_GAS_DRILLING,
	OIL_AND_GAS_EANDP,
	OIL_AND_GAS_INTEGRATED,
	OIL_AND_GAS_MIDSTREAM,
	OIL_AND_GAS_REFINING_AND_MARKETING,
	OIL_AND_GAS_EQUIPMENT_AND_SERVICES,
	THERMAL_COAL,
	URANIUM,
	AEROSPACE_AND_DEFENSE,
	SPECIALTY_BUSINESS_SERVICES,
	CONSULTING_SERVICES,
	RENTAL_AND_LEASING_SERVICES,
	SECURITY_AND_PROTECTION_SERVICES,
	STAFFING_AND_EMPLOYMENT_SERVICES,
	CONGLOMERATES,
	ENGINEERING_AND_CONSTRUCTION,
	INFRASTRUCTURE_OPERATIONS,
	BUILDING_PRODUCTS_AND_EQUIPMENT,
	FARM_AND_HEAVY_CONSTRUCTION_MACHINERY,
	INDUSTRIAL_DISTRIBUTION,
	BUSINESS_EQUIPMENT_AND_SUPPLIES,
	SPECIALTY_INDUSTRIAL_MACHINERY,
	METAL_FABRICATION,
	POLLUTION_AND_TREATMENT_CONTROLS,
	TOOLS_AND_ACCESSORIES,
	ELECTRICAL_EQUIPMENT_AND_PARTS,
	AIRPORTS_AND_AIR_SERVICES,
	AIRLINES,
	RAILROADS,
	MARINE_SHIPPING,
	TRUCKING,
	INTEGRATED_FREIGHT_AND_LOGISTICS,
	WASTE_MANAGEMENT,
	INFORMATION_TECHNOLOGY_SERVICES,
	SOFTWARE_APPLICATION,
	SOFTWARE_INFRASTRUCTURE,
	COMMUNICATION_EQUIPMENT,
	COMPUTER_HARDWARE,
	CONSUMER_ELECTRONICS,
	ELECTRONIC_COMPONENTS,
	ELECTRONICS_AND_COMPUTER_DISTRIBUTION,
	SCIENTIFIC_AND_TECHNICAL_INSTRUMENTS,
	SEMICONDUCTOR_EQUIPMENT_AND_MATERIALS,
	SEMICONDUCTORS,
	SOLAR;
	
	private static final Map<String, Industry> INDUSTRY_MAP = Map.ofEntries(
			Map.entry("Agricultural Inputs", AGRICULTURAL_INPUTS),
			Map.entry("Building Materials", BUILDING_MATERIALS),
			Map.entry("Chemicals", CHEMICALS),
			Map.entry("Specialty Chemicals", SPECIALTY_CHEMICALS),
			Map.entry("Lumber & Wood Production", LUMBER_AND_WOOD_PRODUCTION),
			Map.entry("Paper & Paper Products", PAPER_AND_PAPER_PRODUCTS),
			Map.entry("Aluminum", ALUMINUM),
			Map.entry("Copper", COPPER),
			Map.entry("Other Industrial Metals & Mining", OTHER_INDUSTRIAL_METALS_AND_MINING),
			Map.entry("Gold", GOLD),
			Map.entry("Silver", SILVER),
			Map.entry("Other Precious Metals & Mining", OTHER_PRECIOUS_METALS_AND_MINING),
			Map.entry("Coking Coal", COKING_COAL),
			Map.entry("Steel", STEEL),
			Map.entry("Auto & Truck Dealerships", AUTO_AND_TRUCK_DEALERSHIPS),
			Map.entry("Auto Manufacturers", AUTO_MANUFACTURERS),
			Map.entry("Auto Parts", AUTO_PARTS),
			Map.entry("Recreational Vehicles", RECREATIONAL_VEHICLES),
			Map.entry("Furnishings, Fixtures & Appliances", FURNISHINGS_FIXTURES_AND_APPLIANCES),
			Map.entry("Residential Construction", RESIDENTIAL_CONSTRUCTION),
			Map.entry("Textile Manufacturing", TEXTILE_MANUFACTURING),
			Map.entry("Apparel Manufacturing", APPAREL_MANUFACTURING),
			Map.entry("Footwear & Accessories", FOOTWEAR_AND_ACCESSORIES),
			Map.entry("Packaging & Containers", PACKAGING_AND_CONTAINERS),
			Map.entry("Personal Services", PERSONAL_SERVICES),
			Map.entry("Restaurants", RESTAURANTS),
			Map.entry("Apparel Retail", APPAREL_RETAIL),
			Map.entry("Department Stores", DEPARTMENT_STORES),
			Map.entry("Home Improvement Retail", HOME_IMPROVEMENT_RETAIL),
			Map.entry("Luxury Goods", LUXURY_GOODS),
			Map.entry("Internet Retail", INTERNET_RETAIL),
			Map.entry("Specialty Retail", SPECIALTY_RETAIL),
			Map.entry("Gambling", GAMBLING),
			Map.entry("Leisure", LEISURE),
			Map.entry("Lodging", LODGING),
			Map.entry("Resorts & Casinos", RESORTS_AND_CASINOS),
			Map.entry("Travel Services", TRAVEL_SERVICES),
			Map.entry("Asset Management", ASSET_MANAGEMENT),
			Map.entry("Banks—Diversified", BANKS_DIVERSIFIED),
			Map.entry("Banks—Regional", BANKS_REGIONAL),
			Map.entry("Mortgage Finance", MORTGAGE_FINANCE),
			Map.entry("Capital Markets", CAPITAL_MARKETS),
			Map.entry("Financial Data & Stock Exchanges", FINANCIAL_DATA_AND_STOCK_EXCHANGES),
			Map.entry("Insurance—Life", INSURANCE_LIFE),
			Map.entry("Insurance—Property & Casualty", INSURANCE_PROPERTY_AND_CASUALTY),
			Map.entry("Insurance—Reinsurance", INSURANCE_REINSURANCE),
			Map.entry("Insurance—Specialty", INSURANCE_SPECIALTY),
			Map.entry("Insurance Brokers", INSURANCE_BROKERS),
			Map.entry("Insurance—Diversified", INSURANCE_DIVERSIFIED),
			Map.entry("Shell Companies", SHELL_COMPANIES),
			Map.entry("Financial Conglomerates", FINANCIAL_CONGLOMERATES),
			Map.entry("Credit Services", CREDIT_SERVICES),
			Map.entry("Real Estate—Development", REAL_ESTATE_DEVELOPMENT),
			Map.entry("Real Estate Services", REAL_ESTATE_SERVICES),
			Map.entry("Real Estate—Diversified", REAL_ESTATE_DIVERSIFIED),
			Map.entry("REIT—Healthcare Facilities", REIT_HEALTHCARE_FACILITIES),
			Map.entry("REIT—Hotel & Motel", REIT_HOTEL_AND_MOTEL),
			Map.entry("REIT—Industrial", REIT_INDUSTRIAL),
			Map.entry("REIT—Office", REIT_OFFICE),
			Map.entry("REIT—Residential", REIT_RESIDENTIAL),
			Map.entry("REIT—Retail", REIT_RETAIL),
			Map.entry("REIT—Mortgage", REIT_MORTGAGE),
			Map.entry("REIT—Specialty", REIT_SPECIALTY),
			Map.entry("REIT—Diversified", REIT_DIVERSIFIED),
			Map.entry("Beverages—Brewers", BEVERAGES_BREWERS),
			Map.entry("Beverages—Wineries & Distilleries", BEVERAGES_WINERIES_AND_DISTILLERIES),
			Map.entry("Beverages—Non-Alcoholic", BEVERAGES_NON_ALCOHOLIC),
			Map.entry("Confectioners", CONFECTIONERS),
			Map.entry("Farm Products", FARM_PRODUCTS),
			Map.entry("Household & Personal Products", HOUSEHOLD_AND_PERSONAL_PRODUCTS),
			Map.entry("Packaged Foods", PACKAGED_FOODS),
			Map.entry("Education & Training Services", EDUCATION_AND_TRAINING_SERVICES),
			Map.entry("Discount Stores", DISCOUNT_STORES),
			Map.entry("Food Distribution", FOOD_DISTRIBUTION),
			Map.entry("Grocery Stores", GROCERY_STORES),
			Map.entry("Tobacco", TOBACCO),
			Map.entry("Biotechnology", BIOTECHNOLOGY),
			Map.entry("Drug Manufacturers—General", DRUG_MANUFACTURERS_GENERAL),
			Map.entry("Drug Manufacturers—Specialty & Generic", DRUG_MANUFACTURERS_SPECIALTY_AND_GENERIC),
			Map.entry("Healthcare Plans", HEALTHCARE_PLANS),
			Map.entry("Medical Care Facilities", MEDICAL_CARE_FACILITIES),
			Map.entry("Pharmaceutical Retailers", PHARMACEUTICAL_RETAILERS),
			Map.entry("Health Information Services", HEALTH_INFORMATION_SERVICES),
			Map.entry("Medical Devices", MEDICAL_DEVICES),
			Map.entry("Medical Instruments & Supplies", MEDICAL_INSTRUMENTS_AND_SUPPLIES),
			Map.entry("Diagnostics & Research", DIAGNOSTICS_AND_RESEARCH),
			Map.entry("Medical Distribution", MEDICAL_DISTRIBUTION),
			Map.entry("Utilities—Independent Power Producers", UTILITIES_INDEPENDENT_POWER_PRODUCERS),
			Map.entry("Utilities—Renewable", UTILITIES_RENEWABLE),
			Map.entry("Utilities—Regulated Water", UTILITIES_REGULATED_WATER),
			Map.entry("Utilities—Regulated Electric", UTILITIES_REGULATED_ELECTRIC),
			Map.entry("Utilities—Regulated Gas", UTILITIES_REGULATED_GAS),
			Map.entry("Utilities—Diversified", UTILITIES_DIVERSIFIED),
			Map.entry("Telecom Services", TELECOM_SERVICES),
			Map.entry("Advertising Agencies", ADVERTISING_AGENCIES),
			Map.entry("Publishing", PUBLISHING),
			Map.entry("Broadcasting", BROADCASTING),
			Map.entry("Entertainment", ENTERTAINMENT),
			Map.entry("Internet Content & Information", INTERNET_CONTENT_AND_INFORMATION),
			Map.entry("Electronic Gaming & Multimedia", ELECTRONIC_GAMING_AND_MULTIMEDIA),
			Map.entry("Oil & Gas Drilling", OIL_AND_GAS_DRILLING),
			Map.entry("Oil & Gas E&P", OIL_AND_GAS_EANDP),
			Map.entry("Oil & Gas Integrated", OIL_AND_GAS_INTEGRATED),
			Map.entry("Oil & Gas Midstream", OIL_AND_GAS_MIDSTREAM),
			Map.entry("Oil & Gas Refining & Marketing", OIL_AND_GAS_REFINING_AND_MARKETING),
			Map.entry("Oil & Gas Equipment & Services", OIL_AND_GAS_EQUIPMENT_AND_SERVICES),
			Map.entry("Thermal Coal", THERMAL_COAL),
			Map.entry("Uranium", URANIUM),
			Map.entry("Aerospace & Defense", AEROSPACE_AND_DEFENSE),
			Map.entry("Specialty Business Services", SPECIALTY_BUSINESS_SERVICES),
			Map.entry("Consulting Services", CONSULTING_SERVICES),
			Map.entry("Rental & Leasing Services", RENTAL_AND_LEASING_SERVICES),
			Map.entry("Security & Protection Services", SECURITY_AND_PROTECTION_SERVICES),
			Map.entry("Staffing & Employment Services", STAFFING_AND_EMPLOYMENT_SERVICES),
			Map.entry("Conglomerates", CONGLOMERATES),
			Map.entry("Engineering & Construction", ENGINEERING_AND_CONSTRUCTION),
			Map.entry("Infrastructure Operations", INFRASTRUCTURE_OPERATIONS),
			Map.entry("Building Products & Equipment", BUILDING_PRODUCTS_AND_EQUIPMENT),
			Map.entry("Farm & Heavy Construction Machinery", FARM_AND_HEAVY_CONSTRUCTION_MACHINERY),
			Map.entry("Industrial Distribution", INDUSTRIAL_DISTRIBUTION),
			Map.entry("Business Equipment & Supplies", BUSINESS_EQUIPMENT_AND_SUPPLIES),
			Map.entry("Specialty Industrial Machinery", SPECIALTY_INDUSTRIAL_MACHINERY),
			Map.entry("Metal Fabrication", METAL_FABRICATION),
			Map.entry("Pollution & Treatment Controls", POLLUTION_AND_TREATMENT_CONTROLS),
			Map.entry("Tools & Accessories", TOOLS_AND_ACCESSORIES),
			Map.entry("Electrical Equipment & Parts", ELECTRICAL_EQUIPMENT_AND_PARTS),
			Map.entry("Airports & Air Services", AIRPORTS_AND_AIR_SERVICES),
			Map.entry("Airlines", AIRLINES),
			Map.entry("Railroads", RAILROADS),
			Map.entry("Marine Shipping", MARINE_SHIPPING),
			Map.entry("Trucking", TRUCKING),
			Map.entry("Integrated Freight & Logistics", INTEGRATED_FREIGHT_AND_LOGISTICS),
			Map.entry("Waste Management", WASTE_MANAGEMENT),
			Map.entry("Information Technology Services", INFORMATION_TECHNOLOGY_SERVICES),
			Map.entry("Software—Application", SOFTWARE_APPLICATION),
			Map.entry("Software—Infrastructure", SOFTWARE_INFRASTRUCTURE),
			Map.entry("Communication Equipment", COMMUNICATION_EQUIPMENT),
			Map.entry("Computer Hardware", COMPUTER_HARDWARE),
			Map.entry("Consumer Electronics", CONSUMER_ELECTRONICS),
			Map.entry("Electronic Components", ELECTRONIC_COMPONENTS),
			Map.entry("Electronics & Computer Distribution", ELECTRONICS_AND_COMPUTER_DISTRIBUTION),
			Map.entry("Scientific & Technical Instruments", SCIENTIFIC_AND_TECHNICAL_INSTRUMENTS),
			Map.entry("Semiconductor Equipment & Materials", SEMICONDUCTOR_EQUIPMENT_AND_MATERIALS),
			Map.entry("Semiconductors", SEMICONDUCTORS),
			Map.entry("Solar", SOLAR)
		);
	
	public static Industry getIndustry(String yahooCode) {
		return INDUSTRY_MAP.get(yahooCode);
	}
}
